name: build and push image

on:
  push:
    branches:
      - 'main'
    paths:
      - Dockerfile
      - .github/workflows/docker-build-and-push.yml

env:
  IMAGE_NAME: "simaofsilva/maven-openjdk11-alpine"
  MAVEN_VERSION: "3.9.4" # renovate: datasource=maven depName=org.apache.maven:maven

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout
        uses: actions/checkout@v4    

      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.MAVEN_VERSION }}
            ${{ env.IMAGE_NAME }}:latest
          file: Dockerfile
          build-args: |
            MAVEN_VERSION=${{ env.MAVEN_VERSION }}
