name: build and push container

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  IMAGE_NAME: "simaofsilva/maven-openjdk11-alpine"
  MAVEN_VERSION: "3.8.2"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2    

      - name: Read Dockerfile
        id: dockerfile
        uses: juliangruber/read-file-action@v1
        with:
          path: ./Dockerfile

      - name: Get alpine version for tag
        id: version
        shell: bash
        run: |
          echo "${{ steps.dockerfile.outputs.content }}" > /tmp/content.txt
          echo "::set-output name=VERSION::$(head -n 1 /tmp/content.txt | awk '{print $2}' | cut -d : -f 2)"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.MAVEN_VERSION }}
            ${{ env.IMAGE_NAME }}:latest
          file: Dockerfile
          build-args: |
            MAVEN_VERSION=${{ env.MAVEN_VERSION }}

