name: "test pull request"

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  IMAGE_NAME: "simaofsilva/maven-openjdk11-alpine"
  TAG: "test"
  MAVEN_VERSION: "3.9.3" # renovate: datasource=maven depName=org.apache.maven:maven

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          build-args: |
            MAVEN_VERSION=${{ env.MAVEN_VERSION }}

      - name: Test image
        run: |
          docker run --rm ${{ env.IMAGE_NAME }}:${{ env.TAG }} mvn --version
